### PR TITLE
Update maxquant file parser

### PR DESCRIPTION
**Pull request by jenniferboedker**
Fix based on https://github.com/qbicsoftware/data-model-lib/issues/253

### CODE REVIEW

**Comment by jenniferboedker** [comment]
[Update MaxQuant data structure](https://trello.com/c/qDmC89vI/927-update-maxquant-data-structure)

**Comment by jenniferboedker** [comment]
should I update the documentation too?

**Comment by luiskuhn** [comment]
The implementation looks good to me

**Review by luiskuhn — APPROVED** [review]
The implementation looks solid

**Pull request merged**
